server:
  port: 8092

spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sarbanjeet/OnlineFoodOrderApplication.git
          clone-on-start: true